spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jas
    username: postgres
    password: password
  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: info®